### ISSUE TITLE
Front page text needs updating

### ISSUE THREAD

**Issue by SaraUckelman** [uckelman/dw_op#1]
The front page text currently reads "The Drachenwald Order of Precedence lists of awards held by those living within the kingdom."

It should read: "The Drachenwald Order of Precedence lists awards and honors held by those who currently live in the kingdom or who have lived in the kingdom in the past."

**Comment by SaraUckelman** [comment]
I have fixed this and submitted a pull request.

**Comment by uckelman** [comment]
I've adjusted the text slightly differently, see 66cbca1. Is that ok?

**Comment by uckelman** [comment]
Merged #3.
