### ISSUE TITLE
Sort order for the returned list of hits is wrong.

### ISSUE THREAD

**Issue by SaraUckelman** [uckelman/dw_op#10]
I searched the award recommendation page for 'Simon' and got these hits in this order:

Olaus Simone Silvano
Robert Simon Fraser
Simon Castile
Simon från Skøtve
Simon Karlsson
Simon Montgomerie (also known as Simon Montgumery)
Simon O'Shea
Simon Sigguardsson
Simone
Simon of Adamastor
Simona di Piero Valentini (also known as Simona di Piero Valentina)
Simon Talbot (also known as Joel, Joel Zinngiesser)

Notice what looks wrong here?  "Simone" sorts before "Simona", and both of these do not sort after ALL the Simons.  There is also a problem with capitals vs. non-capitals.  The order should be:

Olaus Simone Silvano
Robert Simon Fraser
Simon Castile
Simon från Skøtve
Simon Karlsson
Simon Montgomerie (also known as Simon Montgumery)
Simon of Adamastor
Simon O'Shea
Simon Sigguardsson
Simon Talbot (also known as Joel, Joel Zinngiesser)
Simona di Piero Valentini (also known as Simona di Piero Valentina)
Simone

**Comment by uckelman** [comment]
Fixed in 23b06fac.
