### ISSUE TITLE
validation of emails put in to the recommendation form doesn't work (yet)

### ISSUE THREAD

**Issue by SaraUckelman** [uckelman/dw_op#12]
Not sure whether it's supposed to, but right now you can put in a lot of bogus emails, such as "unknown@com" and "me@me" and they are accepted.

**Comment by uckelman** [comment]
The form isn't intended to fully validate email addresses. HTML5 input fields reject some things which are illegal according to the RFCs, but are not tight constraints. The rules for valid email addresses are _very_ complicated and it's probably better to simply let the email server figure that out.
