### ISSUE TITLE
Unicode normalization is needed for OP search

### ISSUE THREAD

**Issue by MariaLaine** [uckelman/dw_op#18]
Names containing diacritics and/or special characters (letters from Old English, Old Norse or other such alphabets; characters such as æ, þ, ð etc.) should be found via simpler spelling.

The OP search should allow for easy finding of the person that is looked for. If a person is in the OP but can't be found easily, it increases the risk of creating double entries and of recommendations not specifying the correct person. It's a common problem that people don't know how exactly a name is spelled, especially when diacritics or unusual characters are involved.

**Comment by uckelman** [comment]
I added this in November 2018. E.g., you can search for "Þora Sumarliðadottir" or "Thora Sumarlidhadottir" and get the same results.
