### ISSUE TITLE
OP search should group an individual's multiple names

### ISSUE THREAD

**Issue by MariaLaine** [uckelman/dw_op#19]
When the search returns a list of names, they are listed alphabetically. Especially when several people have "old names" in the database, the list can be quite long even if it in fact contains only a handful of people. I suggest grouping the search results so that the main name list only includes the "current" names of individuals, and after each such "current" name, the "old names" of that individual are listed (e.g. on the same line in parenthesis or on separate lines but indented) so that it's easy to tell apart the individuals from their "old names".

**Comment by SaraUckelman** [comment]
This should already be the case; at least, I asked Joel for this awhile back and he implemented it, so if it's *not* that way any more, then it's because something got reverted to an older form.

**Comment by SaraUckelman** [comment]
See, e.g., the results of my searching for "Mary"; each person is only listed once, no matter how many times they have a 
![screenshot from 2018-10-30 11-37-25](https://user-images.githubusercontent.com/360015/47715655-447b2300-dc38-11e8-8afd-4bfc0ff722a3.png)

If you're not getting this display, can you give a screen shot (or cut and paste) what you're getting?
name that matches the search string.

**Comment by MariaLaine** [comment]
So it is! My bad, I wrote this from memory (remembered it as an annoyance from an earlier testing round when I didn't create GitHub issues) and hadn't noticed it was already implemented. Thank you!

**Comment by SaraUckelman** [comment]
It annoyed me too. :)
