### ISSUE TITLE
Recommendation email should have a copy-pasteable summary

### ISSUE THREAD

**Issue by MariaLaine** [uckelman/dw_op#20]
The old recommendation email included the following section:

> ===================== Addition from the webmaster ====================
> 
> The following is a summary of the information above, all in a format so you can "cut and paste" the information into a spreadsheet or database for your use.  If this is the first time you are seeing this, the fields are:
>  Date/Time | Recommender's Realname | Recommender's SCA name | Recommender's email | SCA Name | Modern Name | Years in the SCA | Gender | Local Group | Region | Award | Events person will attend | Suggested Scribe Name | Suggested Scribe email | Reason for Recommendation
> [And then follows the submitted recommendation formatted in the above described way:
> "13 October 2017 18:24:36|[...]"]

**Comment by uckelman** [comment]
This will be live shortly.

**Comment by uckelman** [comment]
The pasteable summary should appear in recommendation emails now.
