### ISSUE TITLE
corrections to the list of awards: HIGH PRIORITY

### ISSUE THREAD

**Issue by SaraUckelman** [uckelman/dw_op#25]
The "Order of the Aardvark" should not be in the publicly available list of awards, now that the OP is available.

The "Order of Service" needs to be changed to "Ordo Hirundinis"; the "Order of Arts and Sciences" to "Ordo Cygni" and the "Order of Martials Arts" to "Ordo Alae".

**Comment by uckelman** [comment]
The three GoA awards have corrected names now.

I'm making a separate issue for the OoA.
