### ISSUE TITLE
broken URL construction

### ISSUE THREAD

**Issue by SaraUckelman** [uckelman/dw_op#30]
Go to "Search", and then put in a date range, e.g., 2018-10-01–2018-12-31.

On the page that is returned, click on someone's persona name.  This will take you to http://op.drachenwald.sca.org/persona/, which gives a 404 not found.

**Comment by SaraUckelman** [comment]
See also error 46.

**Comment by uckelman** [comment]
Fixed in a084012a. Please verify and close if fixed.
